### ISSUE TITLE
should probably remove "#include <src/extra/libs/qrcode/lv_qrcode.h>" or add it file to project folder.

### ISSUE THREAD

**Issue by colelogan** [rzeldent/esp32-smartdisplay-demo#39]
I've been going through your documentation on working with lvgl and esp-smartdisplay and it's great but would like a little more detail like I'm 5 years old on both this github code folder and https://github.com/rzeldent/esp32-smartdisplay code folder READMES nevertheless thanks so much for the contributions.

**Comment by rzeldent** [comment]
Thanks,

You're right; the include is not required. Has been removed in the develop branch and will hopefully end up in the main!
