### ISSUE TITLE
esp32-2432W328C rotation button not working as expected

### ISSUE THREAD

**Issue by lcscosta** [rzeldent/esp32-smartdisplay-demo#48]
Hello guys,

I have an ESP32-2432W328C, using this demo, the button Add, CDR and built-in Led are working as expected.

But the rotation button creates a bug. I believe that changes in sw_rotate(LVGL 9.2.2) might be causing this resolution problem with the rotate button. I've tried some solutions but none worked. If someone can share your experience using this board in Landscape mode, I will appreciate it.

The following pictures showing the bug:

![vertical](https://github.com/user-attachments/assets/2a632e04-9438-4abb-b8b3-ac1469c5df29)

![horizontal](https://github.com/user-attachments/assets/6b9a0d9f-68d0-4d37-8ad4-cb5cef2b9692)

**Comment by rzeldent** [comment]
Can you test this is resolved in the latest release? [2.1.0](https://github.com/rzeldent/esp32-smartdisplay/releases/tag/2.1.0)

**Comment by lcscosta** [comment]
Problem solved, thank you very much!!!

![Image 2024-11-18 at 22 33 52](https://github.com/user-attachments/assets/64c34da2-ced7-4ae7-b6a5-0c1b14d961be)
