### ISSUE TITLE
 ILI9341_2_DRIVER

### ISSUE THREAD

**Issue by Mschmid0** [rzeldent/esp32-smartdisplay-demo#5]
Would you consider Adding Support for the ILI9341_2_DRIVER?

It has an Alternative Init Sequence.
I have a Newer Revision of [ESP32-2432S028R] with USB-C that Requires it. I Got it working with TFTP_eSPI but not with your Lib because the Init Code is way different.

[TFT_Drivers/ILI9341_Init.h#L127]https://github.com/Bodmer/TFT_eSPI/blob/fa6512faf40594fde13795074e26ef0379708f38/TFT_Drivers/ILI9341_Init.h#L127)

**Comment by rzeldent** [comment]
Is fixed, see https://github.com/rzeldent/esp32-smartdisplay/issues/75

However, so far not able to use it in CI
