### ISSUE TITLE
What board choose for ESP32-2432S028  (Without symbols at end) ?

### ISSUE THREAD

**Issue by warchiefmarkus** [rzeldent/esp32-smartdisplay-demo#53]
Hello, i have this [board ](https://www.aliexpress.com/item/1005006160645147.html?spm=a2g0o.order_list.order_list_main.107.526d1802fbaonE#nav-review )
And see no exact config for this board, and ESP32-2432S028R - dont work (white screen), what version must i choose for this one ?

**Comment by rzeldent** [comment]
Unclear what is in there; they tend to use the available (cheapest?) parts.
If you read the comments in the listing I see TFT ST7789. So maybe it is the esp32-2432S028Rv3 configuration...

Good luck!
